name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install TA-Lib system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential git autoconf automake libtool pkg-config wget ca-certificates

      - name: Build and install TA-Lib C library
        run: |
          cd /tmp
          git clone --depth 1 --branch v0.6.4 https://github.com/TA-Lib/ta-lib.git
          cd ta-lib
          sh autogen.sh
          ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Install Python dependencies
        env:
          TA_LIBRARY_PATH: /usr/local/lib
          TA_INCLUDE_PATH: /usr/local/include
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 app tests

      - name: Run tests
        env:
          MCP_API_KEY: testtoken
          LD_LIBRARY_PATH: /usr/local/lib
        run: pytest -q

      - name: Build Docker image
        run: docker build -t talib-mcp-server .