name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install system dependencies (TA-Lib)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libta-lib0 build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: flake8 app tests

      - name: Format check (black)
        run: black --check app tests

      - name: Run tests
        env:
          MCP_API_KEY: testtoken
        run: pytest -q

      - name: Build Docker image
        run: docker build -t talib-mcp-server .